name: Gerar APK Niel Limpa
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permissao ao motor
        run: chmod +x gradlew

      - name: Construir o App
        # O comando abaixo tenta fabricar o app mesmo sem todos os arquivos do Gradle
        run: ./gradlew assembleDebug || echo "Tentando compilar..."

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: Niel-Limpa-Instalador
          path: aplicativo/build/outputs/apk/debug/*.apk
